language: go

go:
  - "1.13"

addons:
  apt:
    packages:
      - cronolog

env:
  - GO111MODULE=on

before_script:
  - make
script:
  - make test

deploy:
  provider: script
  script: echo "Hi!"
  on:
    branch: master
