language: go

go:
  - "1.11beta3"

addons:
  apt:
    packages:
      - cronolog

before_install:
  - make
script:
  - make test

deploy:
  provider: script
  script: echo "Hi!"
  on:
    branch: master
