language: go

go:
  - "1.11"

addons:
  apt:
    packages:
      - cronolog

before_script:
  - make
script:
  - make test
  - make wire

deploy:
  provider: script
  script: echo "Hi!"
  on:
    branch: master
