// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mywire

import (
	"io"
)

// Injectors from wire.go:

func InitializeEvent(phrase string, w io.Writer) (Event, error) {
	message := NewMessage(phrase)
	greeter, err := NewGreeter(message)
	if err != nil {
		return Event{}, err
	}
	event, err := NewEvent(greeter, w)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
